function Walk () {
    if (WhatDirection == 0) {
        animation.runImageAnimation(
        mySprite,
        [img`
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f...ff..
            ......fd11111111df.fbbf.
            ......fd11111111dffecbf.
            ......fd11111111dfebef..
            ......fbd111111dfebef...
            ....fffcd111111febef....
            ...f2222b11111191ef2f...
            ..f22222222222919f222f..
            ...fbddd22222919dddbf...
            ...fbddddd11919ddddbf...
            ...fbddfdd1919ddfddbf...
            ...fbddfdd9191ddfddbf...
            ...fbddfd91911ddfddbf...
            ...fbddf919111ddfddbf...
            ...fbdf9191111ddffdbf...
            ...fbd919d1111ddffdbf...
            ...fb919ddffffddffdbf...
            ...fb99fddf..fddfdfbf...
            ...fbbbfddf..fddfbbbf...
            ....ffffddf..fddffff....
            .......ffff..ffff.......
            `,img`
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f...ff..
            ......fd11111111df.fbbf.
            ......fd11111111dffecbf.
            ......fd11111111dfebef..
            ......fbd111111dfebef...
            ....fffcd111111febef....
            ...f2222b11111191ef2f...
            ..f22222222222919f222f..
            ...fbddd22222919dddbf...
            ...fbddddd11919ddddbf...
            ...fbddfdd1919ddffdbf...
            ...fbddfdd9191ddffdbf...
            ...fbddfd91911ddffdbf...
            ...fbddf919111ddfdfbf...
            ...fbdf9191111ddfbbbf...
            ...fbd919d1111ddffff....
            ...fb919ddffffddf.......
            ...fb99fddf..ffff.......
            ....ffffddf.............
            .......ffff.............
            `,img`
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f...ff..
            ......fd11111111df.fbbf.
            ......fd11111111dffecbf.
            ......fd11111111dfebef..
            ......fbd111111dfebef...
            ....fffcd111111febef....
            ...f2222b11111191ef2f...
            ..f22222222222919f222f..
            ...fbddd22222919dddbf...
            ...fbddddd11919ddddbf...
            ...fbddfdd1919ddfddbf...
            ...fbddfdd9191ddfddbf...
            ...fbddfd91911ddfddbf...
            ...fbddf919111ddfddbf...
            ...fbdf9191111ddffdbf...
            ...fbd919d1111ddffdbf...
            ...fb919ddffffddffdbf...
            ...fb99fddf..fddfdfbf...
            ...fbbbfddf..fddfbbbf...
            ....ffffddf..fddffff....
            .......ffff..ffff.......
            `,img`
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f...ff..
            ......fd11111111df.fbbf.
            ......fd11111111dffecbf.
            ......fd11111111dfebef..
            ......fbd111111dfebef...
            ....fffcd111111febef....
            ...f2222b11111191ef2f...
            ..f22222222222919f222f..
            ...fbddd22222919dddbf...
            ...fbddddd11919ddddbf...
            ...fbddfdd1919ddfddbf...
            ...fbddfdd9191ddfddbf...
            ...fbddfd91911ddfddbf...
            ...fbddf919111ddfddbf...
            ...fbdf9191111ddffdbf...
            ...fbd919d1111ddffdbf...
            ...fb919ddffffddffdbf...
            ...fb99fddf..fddfdfbf...
            ...fbbbfddf..fddfbbbf...
            ....ffffddf..fddffff....
            .......ffff..ffff.......
            `],
        500,
        false
        )
    } else if (WhatDirection == 1) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        false
        )
    } else if (WhatDirection == 2) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        false
        )
    } else {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        false
        )
    }
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    WhatDirection = 0
    Walk()
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    WhatDirection = 3
    Walk()
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    WhatDirection = 1
    Walk()
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    Walk()
    WhatDirection = 2
})
let WhatDirection = 0
let mySprite: Sprite = null
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f...ff..
    ......fd11111111df.fbbf.
    ......fd19911991dffecbf.
    ......fd11111111dfebef..
    ......fb11111111bfbef...
    ....fffbd111111dbfff....
    ...f4444b111111b2222f...
    ..f444444442222222222f..
    ...f111144442222ddbbf...
    ...f11111444222dddbbf...
    ...f11bf1144421dfdbbf...
    ...f1dbf1144441dfddbf...
    ...f1dbf1114411dfddbf...
    ...f1dff1111111dffdbf...
    ...f1dff1111111dffdbf...
    ...f1dff1111111dffdbf...
    ...f1f1f11ffff1dfdfbf...
    ...f111f11f..f1dfddbf...
    ....ffff11f..f1dffff....
    .......fb1f..f1bf.......
    .......ffff..ffff.......
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 50, 50)
scene.cameraFollowSprite(mySprite)
let mySprite2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
